from __future__ import annotations

import argparse
import email.parser
import hashlib
import json
import os
from pathlib import Path
import re
import zipfile


def _canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def _wheel_identity(path: Path) -> tuple[str, str]:
    with zipfile.ZipFile(path) as archive:
        metadata_names = [
            name
            for name in archive.namelist()
            if name.endswith(".dist-info/METADATA") and len(Path(name).parts) == 2
        ]
        if len(metadata_names) != 1:
            raise ValueError(f"wheel must contain one METADATA file: {path.name}")
        message = email.parser.BytesParser().parsebytes(archive.read(metadata_names[0]))
    name = message.get("Name")
    version = message.get("Version")
    if not name or not version:
        raise ValueError(f"wheel metadata lacks name/version: {path.name}")
    return str(name), str(version)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def generate(wheelhouse: Path) -> tuple[str, dict[str, object]]:
    wheels = sorted(wheelhouse.glob("*.whl"), key=lambda item: item.name.casefold())
    if not wheels:
        raise ValueError("wheelhouse contains no wheel files")
    records: list[dict[str, object]] = []
    requirements: dict[tuple[str, str], list[str]] = {}
    display_names: dict[tuple[str, str], str] = {}
    for path in wheels:
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"wheelhouse entries must be regular files: {path.name}")
        name, version = _wheel_identity(path)
        key = (_canonical_name(name), version)
        digest = _sha256(path)
        requirements.setdefault(key, []).append(digest)
        display_names[key] = name
        records.append(
            {
                "filename": path.name,
                "distribution": name,
                "version": version,
                "bytes": path.stat().st_size,
                "sha256": digest,
            }
        )
    lines = [
        "# Generated by scripts/generate_release_lock.py.",
        "# Install only with --isolated --no-index --require-hashes.",
    ]
    for key in sorted(requirements):
        hashes = sorted(set(requirements[key]))
        name = display_names[key]
        if len(hashes) == 1:
            lines.append(f"{name}=={key[1]} --hash=sha256:{hashes[0]}")
        else:
            lines.append(f"{name}=={key[1]} \\")
            for index, digest in enumerate(hashes):
                suffix = " \\" if index < len(hashes) - 1 else ""
                lines.append(f"    --hash=sha256:{digest}{suffix}")
    lock_text = "\n".join(lines) + "\n"
    manifest: dict[str, object] = {
        "schema": "guandan.wheelhouse-lock/1",
        "platform": "win_amd64",
        "python": "3.12",
        "files": records,
        "aggregate_sha256": hashlib.sha256(
            json.dumps(records, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest(),
        "requirements_lock_sha256": hashlib.sha256(lock_text.encode("utf-8")).hexdigest(),
    }
    return lock_text, manifest


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        with temporary.open("xb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheelhouse", type=Path, required=True)
    parser.add_argument("--requirements-lock", type=Path, required=True)
    parser.add_argument("--wheelhouse-lock", type=Path, required=True)
    args = parser.parse_args()
    text, manifest = generate(args.wheelhouse)
    _atomic_write(args.requirements_lock, text.encode("utf-8"))
    _atomic_write(
        args.wheelhouse_lock,
        (json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
