"""Public contracts for the replacement live action pipeline."""

from .architecture import assert_package_boundaries, check_package_boundaries
from .engine import EngineInput, EngineResult, EngineState, LiveEngine
from .event_resolver import ResolutionResult, UnifiedActionResolver
from .game_state import GameAction, GameSnapshot, SeatCardCount, TrustedGameSnapshot
from .gap_lifecycle import GapLifecycle
from .input_lifecycle import (
    CandidateReceipt,
    EvidenceLifecycle,
    InputKind,
    InputRejection,
    InputRejectionReason,
)
from .opportunity import (
    OpportunityLifecycle,
    OpportunityState,
    OpportunityTransition,
    SideEffectDispatcher,
    SideEffectFailure,
    SideEffectFailureKind,
)
from .protocols import (
    AdviceConsumer,
    EventJournal,
    ObservationInput,
    ProcessingClock,
    RuleProjector,
    RuleStateProvider,
    TransactionalActionCommitter,
)
from .reconciliation import BoundedGapReconciler, ReconciliationAttempt
from .types import (
    ActionCandidate,
    ActionInterpretation,
    ActionKind,
    ActionSemantics,
    AdviceOpportunity,
    CandidateReason,
    CommitReason,
    CommitResult,
    ConfirmationReason,
    ConfirmedAction,
    EngineUpdate,
    EngineUpdateReason,
    EvidenceDropReason,
    EvidenceOrigin,
    FrameIdentity,
    GapPhase,
    GapReason,
    GapState,
    ObservationKind,
    ObservationReason,
    OpportunityReason,
    OpportunityStatus,
    ProjectionReason,
    ProjectionResult,
    ScheduledItemKind,
    SchedulingDropReason,
    Seat,
    SeatObservation,
    StateVersion,
    VersionIdentity,
)

__all__ = [
    "ActionCandidate",
    "ActionInterpretation",
    "ActionKind",
    "ActionSemantics",
    "AdviceConsumer",
    "AdviceOpportunity",
    "BoundedGapReconciler",
    "CandidateReceipt",
    "CandidateReason",
    "CommitReason",
    "CommitResult",
    "ConfirmationReason",
    "ConfirmedAction",
    "assert_package_boundaries",
    "check_package_boundaries",
    "EngineUpdate",
    "EngineUpdateReason",
    "EngineInput",
    "EngineResult",
    "EngineState",
    "EvidenceDropReason",
    "EvidenceOrigin",
    "EventJournal",
    "FrameIdentity",
    "GameAction",
    "GameSnapshot",
    "GapLifecycle",
    "GapPhase",
    "GapReason",
    "GapState",
    "ObservationInput",
    "ObservationKind",
    "ObservationReason",
    "OpportunityReason",
    "OpportunityStatus",
    "OpportunityLifecycle",
    "OpportunityState",
    "OpportunityTransition",
    "ProcessingClock",
    "ProjectionReason",
    "ProjectionResult",
    "RuleProjector",
    "RuleStateProvider",
    "ReconciliationAttempt",
    "ScheduledItemKind",
    "SchedulingDropReason",
    "Seat",
    "SeatCardCount",
    "SeatObservation",
    "StateVersion",
    "SideEffectDispatcher",
    "SideEffectFailure",
    "SideEffectFailureKind",
    "TransactionalActionCommitter",
    "TrustedGameSnapshot",
    "UnifiedActionResolver",
    "VersionIdentity",
    "EvidenceLifecycle",
    "InputKind",
    "InputRejection",
    "InputRejectionReason",
    "LiveEngine",
    "ResolutionResult",
]
